#-------------------------------------------------
#
# Project created by QtCreator 2015-10-27T23:22:01
#
#-------------------------------------------------

QT       += core gui dbus

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
greaterThan(QT_MAJOR_VERSION, 4): QT += printsupport

TARGET = ikPaint
TEMPLATE = app

ICON = ikPaint.icns

INCLUDEPATH += $$PWD/commands \
    $$PWD/imagelib \
    $$PWD/imagelib/effects \
    $$PWD/imagelib/transforms \
    $$PWD/tools \
    $$PWD/cursors \
    $$PWD/dialogs/imagelib \
    $$PWD/document \
    $$PWD/docs \
    $$PWD/environments \
    $$PWD/environments/commands \
    $$PWD/environments/dialogs/imagelib \
    $$PWD/environments/document \
    $$PWD/environments/tools \
    $$PWD/environments/tools/selection \
    $$PWD/generic \
    $$PWD/generic/widgets \
    $$PWD/layers/selections \
    $$PWD/layers/selections/image \
    $$PWD/layers/selections/text \
    $$PWD/layers/tempImage \
    $$PWD/lgpl \
    $$PWD/lgpl/generic \
    $$PWD/lgpl/generic/widgets \
    $$PWD/mainWindow \
    $$PWD/pixmapfx \
    $$PWD/tools/flow \
    $$PWD/tools/polygonal \
    $$PWD/tools/rectangular \
    $$PWD/tools/selection \
    $$PWD/tools/selection/image \
    $$PWD/tools/selection/text \
    $$PWD/views \
    $$PWD/views/manager \
    $$PWD/widgets \
    $$PWD/widgets/colorSimilarity \
    $$PWD/widgets/imagelib/effects \
    $$PWD/widgets/toolbars \
    $$PWD/widgets/toolbars/options \
    $$PWD/commands/imagelib \
    $$PWD/commands/imagelib/effects \
    $$PWD/commands/imagelib/transforms \
    $$PWD/commands/tools \
    $$PWD/commands/tools/flow \
    $$PWD/commands/tools/polygonal \
    $$PWD/commands/tools/rectangular \
    $$PWD/commands/tools/selection \
    $$PWD/commands/tools/selection/text \
    $$PWD/dialogs/imagelib/effects \
    $$PWD/dialogs/imagelib/transforms \
    $$PWD/dialogs \
    $$PWD/environments/dialogs/imagelib/transforms \
    $$PWD/utl
HEADERS += \
    utl/kaction.h \
    utl/kaction_p.h \
    utl/kfontaction.h \
    utl/kfontsizeaction.h \
    utl/kselectaction.h \
    utl/kactioncollection.h \
    utl/qqolorbutton.h \
    kpViewScrollableContainer.h \
    cursors/kpCursorLightCross.h \
    cursors/kpCursorProvider.h \
    dialogs/imagelib/effects/kpEffectsDialog.h \
    dialogs/imagelib/kpDocumentMetaInfoDialog.h \
    dialogs/imagelib/transforms/kpTransformPreviewDialog.h \
    dialogs/imagelib/transforms/kpTransformResizeScaleDialog.h \
    dialogs/imagelib/transforms/kpTransformRotateDialog.h \
    dialogs/imagelib/transforms/kpTransformSkewDialog.h \
    dialogs/kpColorSimilarityDialog.h \
    dialogs/kpDocumentSaveOptionsPreviewDialog.h \
    document/kpDocument.h \
    document/kpDocumentPrivate.h \
    environments/commands/kpCommandEnvironment.h \
    environments/dialogs/imagelib/transforms/kpTransformDialogEnvironment.h \
    environments/document/kpDocumentEnvironment.h \
    environments/kpEnvironmentBase.h \
    environments/tools/kpToolEnvironment.h \
    environments/tools/selection/kpToolSelectionEnvironment.h \
    generic/kpSetOverrideCursorSaver.h \
    generic/kpWidgetMapper.h \
    generic/widgets/kpResizeSignallingLabel.h \
    generic/widgets/kpSubWindow.h \
    imagelib/effects/kpEffectBalance.h \
    imagelib/effects/kpEffectBlurSharpen.h \
    imagelib/effects/kpEffectEmboss.h \
    imagelib/effects/kpEffectFlatten.h \
    imagelib/effects/kpEffectGrayscale.h \
    imagelib/effects/kpEffectHSV.h \
    imagelib/effects/kpEffectInvert.h \
    imagelib/effects/kpEffectReduceColors.h \
    imagelib/effects/kpEffectToneEnhance.h \
    imagelib/kpColor.h \
    imagelib/kpDocumentMetaInfo.h \
    imagelib/kpFloodFill.h \
    imagelib/kpImage.h \
    imagelib/kpPainter.h \
    imagelib/transforms/kpTransformAutoCrop.h \
    imagelib/transforms/kpTransformCrop.h \
    imagelib/transforms/kpTransformCropPrivate.h \
    kpDefs.h \
    layers/selections/image/kpAbstractImageSelection.h \
    layers/selections/image/kpEllipticalImageSelection.h \
    layers/selections/image/kpFreeFormImageSelection.h \
    layers/selections/image/kpImageSelectionTransparency.h \
    layers/selections/image/kpRectangularImageSelection.h \
    layers/selections/kpAbstractSelection.h \
    layers/selections/kpSelectionDrag.h \
    layers/selections/kpSelectionFactory.h \
    layers/selections/text/kpPreeditText.h \
    layers/selections/text/kpTextSelection.h \
    layers/selections/text/kpTextSelectionPrivate.h \
    layers/selections/text/kpTextStyle.h \
    layers/tempImage/kpTempImage.h \
    lgpl/generic/kpColorCollection.h \
    lgpl/generic/kpUrlFormatter.h \
    lgpl/generic/widgets/kpColorCellsBase.h \
    lgpl/kolourpaint_lgpl_export.h \
    mainWindow/kpMainWindow.h \
    mainWindow/kpMainWindowPrivate.h \
    pixmapfx/kpPixmapFX.h \
    tools/flow/kpToolBrush.h \
    tools/flow/kpToolColorEraser.h \
    tools/flow/kpToolEraser.h \
    tools/flow/kpToolFlowBase.h \
    tools/flow/kpToolFlowPixmapBase.h \
    tools/flow/kpToolPen.h \
    tools/flow/kpToolSpraycan.h \
    tools/kpTool.h \
    tools/kpToolAction.h \
    tools/kpToolColorPicker.h \
    tools/kpToolFloodFill.h \
    tools/kpToolPrivate.h \
    tools/kpToolZoom.h \
    tools/polygonal/kpToolCurve.h \
    tools/polygonal/kpToolLine.h \
    tools/polygonal/kpToolPolygon.h \
    tools/polygonal/kpToolPolygonalBase.h \
    tools/polygonal/kpToolPolyline.h \
    tools/rectangular/kpToolEllipse.h \
    tools/rectangular/kpToolRectangle.h \
    tools/rectangular/kpToolRectangularBase.h \
    tools/rectangular/kpToolRoundedRectangle.h \
    tools/selection/image/kpAbstractImageSelectionTool.h \
    tools/selection/image/kpToolEllipticalSelection.h \
    tools/selection/image/kpToolFreeFormSelection.h \
    tools/selection/image/kpToolRectSelection.h \
    tools/selection/kpAbstractSelectionTool.h \
    tools/selection/kpAbstractSelectionToolPrivate.h \
    tools/selection/text/kpToolText.h \
    tools/selection/text/kpToolTextPrivate.h \
    utl/kdialog.h \
    utl/tools.h \
    views/kpView.h \
    views/kpViewPrivate.h \
    views/kpZoomedView.h \
    views/manager/kpViewManager.h \
    views/manager/kpViewManagerPrivate.h \
    widgets/colorSimilarity/kpColorSimilarityCubeRenderer.h \
    widgets/colorSimilarity/kpColorSimilarityFrame.h \
    widgets/colorSimilarity/kpColorSimilarityHolder.h \
    widgets/colorSimilarity/kpColorSimilarityToolBarItem.h \
    widgets/imagelib/effects/kpEffectBalanceWidget.h \
    widgets/imagelib/effects/kpEffectBlurSharpenWidget.h \
    widgets/imagelib/effects/kpEffectEmbossWidget.h \
    widgets/imagelib/effects/kpEffectFlattenWidget.h \
    widgets/imagelib/effects/kpEffectHSVWidget.h \
    widgets/imagelib/effects/kpEffectInvertWidget.h \
    widgets/imagelib/effects/kpEffectReduceColorsWidget.h \
    widgets/imagelib/effects/kpEffectToneEnhanceWidget.h \
    widgets/imagelib/effects/kpEffectWidgetBase.h \
    widgets/kpColorCells.h \
    widgets/kpColorPalette.h \
    widgets/kpDefaultColorCollection.h \
    widgets/kpDualColorButton.h \
    widgets/kpPrintDialogPage.h \
    widgets/kpTransparentColorCell.h \
    widgets/toolbars/kpColorToolBar.h \
    widgets/toolbars/kpToolToolBar.h \
    widgets/toolbars/options/kpToolWidgetBase.h \
    widgets/toolbars/options/kpToolWidgetBrush.h \
    widgets/toolbars/options/kpToolWidgetEraserSize.h \
    widgets/toolbars/options/kpToolWidgetFillStyle.h \
    widgets/toolbars/options/kpToolWidgetLineWidth.h \
    widgets/toolbars/options/kpToolWidgetOpaqueOrTransparent.h \
    widgets/toolbars/options/kpToolWidgetSpraycanSize.h \
    commands/imagelib/effects/kpEffectBalanceCommand.h \
    commands/imagelib/effects/kpEffectBlurSharpenCommand.h \
    commands/imagelib/effects/kpEffectClearCommand.h \
    commands/imagelib/effects/kpEffectCommandBase.h \
    commands/imagelib/effects/kpEffectEmbossCommand.h \
    commands/imagelib/effects/kpEffectFlattenCommand.h \
    commands/imagelib/effects/kpEffectGrayscaleCommand.h \
    commands/imagelib/effects/kpEffectHSVCommand.h \
    commands/imagelib/effects/kpEffectInvertCommand.h \
    commands/imagelib/effects/kpEffectReduceColorsCommand.h \
    commands/imagelib/effects/kpEffectToneEnhanceCommand.h \
    commands/imagelib/kpDocumentMetaInfoCommand.h \
    commands/imagelib/transforms/kpTransformFlipCommand.h \
    commands/imagelib/transforms/kpTransformResizeScaleCommand.h \
    commands/imagelib/transforms/kpTransformRotateCommand.h \
    commands/imagelib/transforms/kpTransformSkewCommand.h \
    commands/kpCommand.h \
    commands/kpCommandHistory.h \
    commands/kpCommandHistoryBase.h \
    commands/kpCommandSize.h \
    commands/kpMacroCommand.h \
    commands/kpNamedCommand.h \
    commands/tools/flow/kpToolFlowCommand.h \
    commands/tools/kpToolColorPickerCommand.h \
    commands/tools/kpToolFloodFillCommand.h \
    commands/tools/polygonal/kpToolPolygonalCommand.h \
    commands/tools/rectangular/kpToolRectangularCommand.h \
    commands/tools/selection/kpAbstractSelectionContentCommand.h \
    commands/tools/selection/kpToolImageSelectionTransparencyCommand.h \
    commands/tools/selection/kpToolSelectionCreateCommand.h \
    commands/tools/selection/kpToolSelectionDestroyCommand.h \
    commands/tools/selection/kpToolSelectionMoveCommand.h \
    commands/tools/selection/kpToolSelectionPullFromDocumentCommand.h \
    commands/tools/selection/kpToolSelectionResizeScaleCommand.h \
    commands/tools/selection/text/kpToolTextBackspaceCommand.h \
    commands/tools/selection/text/kpToolTextChangeStyleCommand.h \
    commands/tools/selection/text/kpToolTextDeleteCommand.h \
    commands/tools/selection/text/kpToolTextEnterCommand.h \
    commands/tools/selection/text/kpToolTextGiveContentCommand.h \
    commands/tools/selection/text/kpToolTextInsertCommand.h \
    utl/krecentfilesaction.h \
    widgets/kpStatusBarLabels.h \
    imagelib/effects/kpEffectColorToAlpha.h \
    commands/imagelib/effects/kpEffectColorToAlphaCommand.h \
    widgets/imagelib/effects/kpEffectColorToAlphaWidget.h \
    dialogs/kpAboutDialog.h \
    kpApplication.h
SOURCES += utl/kaction.cpp \
    utl/kfontaction.cpp \
    utl/kfontsizeaction.cpp \
    utl/kselectaction.cpp \
    utl/kactioncollection.cpp \
    utl/qqolorbutton.cpp \
    kpViewScrollableContainer.cpp \
    cursors/kpCursorLightCross.cpp \
    cursors/kpCursorProvider.cpp \
    dialogs/imagelib/effects/kpEffectsDialog.cpp \
    dialogs/imagelib/kpDocumentMetaInfoDialog.cpp \
    dialogs/imagelib/transforms/kpTransformPreviewDialog.cpp \
    dialogs/imagelib/transforms/kpTransformResizeScaleDialog.cpp \
    dialogs/imagelib/transforms/kpTransformRotateDialog.cpp \
    dialogs/imagelib/transforms/kpTransformSkewDialog.cpp \
    dialogs/kpColorSimilarityDialog.cpp \
    dialogs/kpDocumentSaveOptionsPreviewDialog.cpp \
    document/kpDocument.cpp \
    document/kpDocument_Open.cpp \
    document/kpDocument_Save.cpp \
    document/kpDocument_Selection.cpp \
    environments/commands/kpCommandEnvironment.cpp \
    environments/dialogs/imagelib/transforms/kpTransformDialogEnvironment.cpp \
    environments/document/kpDocumentEnvironment.cpp \
    environments/kpEnvironmentBase.cpp \
    environments/tools/kpToolEnvironment.cpp \
    environments/tools/selection/kpToolSelectionEnvironment.cpp \
    generic/kpSetOverrideCursorSaver.cpp \
    generic/kpWidgetMapper.cpp \
    generic/widgets/kpResizeSignallingLabel.cpp \
    generic/widgets/kpSubWindow.cpp \
    imagelib/effects/kpEffectBalance.cpp \
    imagelib/effects/kpEffectBlurSharpen.cpp \
    imagelib/effects/kpEffectEmboss.cpp \
    imagelib/effects/kpEffectFlatten.cpp \
    imagelib/effects/kpEffectGrayscale.cpp \
    imagelib/effects/kpEffectHSV.cpp \
    imagelib/effects/kpEffectInvert.cpp \
    imagelib/effects/kpEffectReduceColors.cpp \
    imagelib/effects/kpEffectToneEnhance.cpp \
    imagelib/kpColor.cpp \
    imagelib/kpColor_Constants.cpp \
    imagelib/kpDocumentMetaInfo.cpp \
    imagelib/kpFloodFill.cpp \
    imagelib/kpPainter.cpp \
    imagelib/transforms/kpTransformAutoCrop.cpp \
    imagelib/transforms/kpTransformCrop.cpp \
    imagelib/transforms/kpTransformCrop_ImageSelection.cpp \
    imagelib/transforms/kpTransformCrop_TextSelection.cpp \
    layers/selections/image/kpAbstractImageSelection.cpp \
    layers/selections/image/kpEllipticalImageSelection.cpp \
    layers/selections/image/kpFreeFormImageSelection.cpp \
    layers/selections/image/kpImageSelectionTransparency.cpp \
    layers/selections/image/kpRectangularImageSelection.cpp \
    layers/selections/kpAbstractSelection.cpp \
    layers/selections/kpSelectionDrag.cpp \
    layers/selections/kpSelectionFactory.cpp \
    layers/selections/text/kpPreeditText.cpp \
    layers/selections/text/kpTextSelection.cpp \
    layers/selections/text/kpTextSelection_Cursor.cpp \
    layers/selections/text/kpTextSelection_Paint.cpp \
    layers/selections/text/kpTextStyle.cpp \
    layers/tempImage/kpTempImage.cpp \
    lgpl/generic/kpColorCollection.cpp \
    lgpl/generic/kpUrlFormatter.cpp \
    lgpl/generic/widgets/kpColorCellsBase.cpp \
    mainWindow/kpMainWindow.cpp \
    mainWindow/kpMainWindow_Colors.cpp \
    mainWindow/kpMainWindow_Edit.cpp \
    mainWindow/kpMainWindow_File.cpp \
    mainWindow/kpMainWindow_Image.cpp \
    mainWindow/kpMainWindow_Settings.cpp \
    mainWindow/kpMainWindow_StatusBar.cpp \
    mainWindow/kpMainWindow_Text.cpp \
    mainWindow/kpMainWindow_Tools.cpp \
    mainWindow/kpMainWindow_View.cpp \
    mainWindow/kpMainWindow_View_Zoom.cpp \
    pixmapfx/kpPixmapFX_DrawRasterOps.cpp \
    pixmapfx/kpPixmapFX_DrawShapes.cpp \
    pixmapfx/kpPixmapFX_Effects.cpp \
    pixmapfx/kpPixmapFX_GetSetPixmapParts.cpp \
    pixmapfx/kpPixmapFX_Transforms.cpp \
    tools/flow/kpToolBrush.cpp \
    tools/flow/kpToolColorEraser.cpp \
    tools/flow/kpToolEraser.cpp \
    tools/flow/kpToolFlowBase.cpp \
    tools/flow/kpToolFlowPixmapBase.cpp \
    tools/flow/kpToolPen.cpp \
    tools/flow/kpToolSpraycan.cpp \
    tools/kpTool.cpp \
    tools/kpToolAction.cpp \
    tools/kpToolColorPicker.cpp \
    tools/kpToolFloodFill.cpp \
    tools/kpToolZoom.cpp \
    tools/kpTool_Drawing.cpp \
    tools/kpTool_KeyboardEvents.cpp \
    tools/kpTool_MouseEvents.cpp \
    tools/kpTool_OtherEvents.cpp \
    tools/kpTool_UserNotifications.cpp \
    tools/kpTool_Utilities.cpp \
    tools/polygonal/kpToolCurve.cpp \
    tools/polygonal/kpToolLine.cpp \
    tools/polygonal/kpToolPolygon.cpp \
    tools/polygonal/kpToolPolygonalBase.cpp \
    tools/polygonal/kpToolPolyline.cpp \
    tools/rectangular/kpToolEllipse.cpp \
    tools/rectangular/kpToolRectangle.cpp \
    tools/rectangular/kpToolRectangularBase.cpp \
    tools/rectangular/kpToolRoundedRectangle.cpp \
    tools/selection/image/kpAbstractImageSelectionTool.cpp \
    tools/selection/image/kpAbstractImageSelectionTool_Transparency.cpp \
    tools/selection/image/kpToolEllipticalSelection.cpp \
    tools/selection/image/kpToolFreeFormSelection.cpp \
    tools/selection/image/kpToolRectSelection.cpp \
    tools/selection/kpAbstractSelectionTool.cpp \
    tools/selection/kpAbstractSelectionTool_Create.cpp \
    tools/selection/kpAbstractSelectionTool_KeyboardEvents.cpp \
    tools/selection/kpAbstractSelectionTool_Move.cpp \
    tools/selection/kpAbstractSelectionTool_ResizeScale.cpp \
    tools/selection/text/kpToolText.cpp \
    tools/selection/text/kpToolText_Commands.cpp \
    tools/selection/text/kpToolText_Create.cpp \
    tools/selection/text/kpToolText_CursorCalc.cpp \
    tools/selection/text/kpToolText_InputMethodEvents.cpp \
    tools/selection/text/kpToolText_KeyboardEvents.cpp \
    tools/selection/text/kpToolText_KeyboardEvents_HandleArrowKeys.cpp \
    tools/selection/text/kpToolText_KeyboardEvents_HandleTypingKeys.cpp \
    tools/selection/text/kpToolText_Move.cpp \
    tools/selection/text/kpToolText_ResizeScale.cpp \
    tools/selection/text/kpToolText_SelectText.cpp \
    tools/selection/text/kpToolText_TextStyle.cpp \
    utl/kdialog.cpp \
    views/kpView.cpp \
    views/kpView_Events.cpp \
    views/kpView_Paint.cpp \
    views/kpView_Selections.cpp \
    views/kpZoomedView.cpp \
    views/manager/kpViewManager.cpp \
    views/manager/kpViewManager_TextCursor.cpp \
    views/manager/kpViewManager_ViewUpdates.cpp \
    widgets/colorSimilarity/kpColorSimilarityCubeRenderer.cpp \
    widgets/colorSimilarity/kpColorSimilarityFrame.cpp \
    widgets/colorSimilarity/kpColorSimilarityHolder.cpp \
    widgets/colorSimilarity/kpColorSimilarityToolBarItem.cpp \
    widgets/imagelib/effects/kpEffectBalanceWidget.cpp \
    widgets/imagelib/effects/kpEffectBlurSharpenWidget.cpp \
    widgets/imagelib/effects/kpEffectEmbossWidget.cpp \
    widgets/imagelib/effects/kpEffectFlattenWidget.cpp \
    widgets/imagelib/effects/kpEffectHSVWidget.cpp \
    widgets/imagelib/effects/kpEffectInvertWidget.cpp \
    widgets/imagelib/effects/kpEffectReduceColorsWidget.cpp \
    widgets/imagelib/effects/kpEffectToneEnhanceWidget.cpp \
    widgets/imagelib/effects/kpEffectWidgetBase.cpp \
    widgets/kpColorCells.cpp \
    widgets/kpColorPalette.cpp \
    widgets/kpDefaultColorCollection.cpp \
    widgets/kpDualColorButton.cpp \
    widgets/kpPrintDialogPage.cpp \
    widgets/kpTransparentColorCell.cpp \
    widgets/toolbars/kpColorToolBar.cpp \
    widgets/toolbars/kpToolToolBar.cpp \
    widgets/toolbars/options/kpToolWidgetBase.cpp \
    widgets/toolbars/options/kpToolWidgetBrush.cpp \
    widgets/toolbars/options/kpToolWidgetEraserSize.cpp \
    widgets/toolbars/options/kpToolWidgetFillStyle.cpp \
    widgets/toolbars/options/kpToolWidgetLineWidth.cpp \
    widgets/toolbars/options/kpToolWidgetOpaqueOrTransparent.cpp \
    widgets/toolbars/options/kpToolWidgetSpraycanSize.cpp \
    commands/imagelib/effects/kpEffectBalanceCommand.cpp \
    commands/imagelib/effects/kpEffectBlurSharpenCommand.cpp \
    commands/imagelib/effects/kpEffectClearCommand.cpp \
    commands/imagelib/effects/kpEffectCommandBase.cpp \
    commands/imagelib/effects/kpEffectEmbossCommand.cpp \
    commands/imagelib/effects/kpEffectFlattenCommand.cpp \
    commands/imagelib/effects/kpEffectGrayscaleCommand.cpp \
    commands/imagelib/effects/kpEffectHSVCommand.cpp \
    commands/imagelib/effects/kpEffectInvertCommand.cpp \
    commands/imagelib/effects/kpEffectReduceColorsCommand.cpp \
    commands/imagelib/effects/kpEffectToneEnhanceCommand.cpp \
    commands/imagelib/kpDocumentMetaInfoCommand.cpp \
    commands/imagelib/transforms/kpTransformFlipCommand.cpp \
    commands/imagelib/transforms/kpTransformResizeScaleCommand.cpp \
    commands/imagelib/transforms/kpTransformRotateCommand.cpp \
    commands/imagelib/transforms/kpTransformSkewCommand.cpp \
    commands/kpCommand.cpp \
    commands/kpCommandHistory.cpp \
    commands/kpCommandHistoryBase.cpp \
    commands/kpCommandSize.cpp \
    commands/kpMacroCommand.cpp \
    commands/kpNamedCommand.cpp \
    commands/tools/flow/kpToolFlowCommand.cpp \
    commands/tools/kpToolColorPickerCommand.cpp \
    commands/tools/kpToolFloodFillCommand.cpp \
    commands/tools/polygonal/kpToolPolygonalCommand.cpp \
    commands/tools/rectangular/kpToolRectangularCommand.cpp \
    commands/tools/selection/kpAbstractSelectionContentCommand.cpp \
    commands/tools/selection/kpToolImageSelectionTransparencyCommand.cpp \
    commands/tools/selection/kpToolSelectionCreateCommand.cpp \
    commands/tools/selection/kpToolSelectionDestroyCommand.cpp \
    commands/tools/selection/kpToolSelectionMoveCommand.cpp \
    commands/tools/selection/kpToolSelectionPullFromDocumentCommand.cpp \
    commands/tools/selection/kpToolSelectionResizeScaleCommand.cpp \
    commands/tools/selection/text/kpToolTextBackspaceCommand.cpp \
    commands/tools/selection/text/kpToolTextChangeStyleCommand.cpp \
    commands/tools/selection/text/kpToolTextDeleteCommand.cpp \
    commands/tools/selection/text/kpToolTextEnterCommand.cpp \
    commands/tools/selection/text/kpToolTextGiveContentCommand.cpp \
    commands/tools/selection/text/kpToolTextInsertCommand.cpp \
    main.cpp \
    utl/krecentfilesaction.cpp \
    widgets/kpStatusBarLabels.cpp \
    imagelib/effects/kpEffectColorToAlpha.cpp \
    commands/imagelib/effects/kpEffectColorToAlphaCommand.cpp \
    widgets/imagelib/effects/kpEffectColorToAlphaWidget.cpp \
    dialogs/kpAboutDialog.cpp \
    kpApplication.cpp
FORMS +=
RESOURCES += images.qrc
